CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(200) NOT NULL,
	available boolean NOT NULL DEFAULT FALSE,
	owner_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
  	id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  	date_start TIMESTAMP NOT NULL,
  	date_end TIMESTAMP NOT NULL,
  	item_id bigint NOT NULL REFERENCES items (id),
  	booker_id bigint NOT NULL REFERENCES users (id),
  	status VARCHAR(10) NOT NULL,
  	CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text_comment VARCHAR(2000) NOT NULL,
    item_id bigint NOT NULL REFERENCES items (id),
    user_id bigint NOT NULL REFERENCES users (id),
    CONSTRAINT pk_comments PRIMARY KEY (id)
);